/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	clickhouseradondbcomv1 "github.com/radondb/clickhouse-operator/pkg/apis/clickhouse.radondb.com/v1"
	versioned "github.com/radondb/clickhouse-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/radondb/clickhouse-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/radondb/clickhouse-operator/pkg/client/listers/clickhouse.radondb.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClickHouseBackupInformer provides access to a shared informer and lister for
// ClickHouseBackups.
type ClickHouseBackupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ClickHouseBackupLister
}

type clickHouseBackupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClickHouseBackupInformer constructs a new informer for ClickHouseBackup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClickHouseBackupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClickHouseBackupInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClickHouseBackupInformer constructs a new informer for ClickHouseBackup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClickHouseBackupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClickhouseV1().ClickHouseBackups(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClickhouseV1().ClickHouseBackups(namespace).Watch(context.TODO(), options)
			},
		},
		&clickhouseradondbcomv1.ClickHouseBackup{},
		resyncPeriod,
		indexers,
	)
}

func (f *clickHouseBackupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClickHouseBackupInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clickHouseBackupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clickhouseradondbcomv1.ClickHouseBackup{}, f.defaultInformer)
}

func (f *clickHouseBackupInformer) Lister() v1.ClickHouseBackupLister {
	return v1.NewClickHouseBackupLister(f.Informer().GetIndexer())
}
