// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clickhouseqingcloudcomv1 "github.com/TCeason/clickhouse-operator/pkg/apis/clickhouse.qingcloud.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClickHouseOperatorConfigurations implements ClickHouseOperatorConfigurationInterface
type FakeClickHouseOperatorConfigurations struct {
	Fake *FakeClickhouseV1
	ns   string
}

var clickhouseoperatorconfigurationsResource = schema.GroupVersionResource{Group: "clickhouse.qingcloud.com", Version: "v1", Resource: "clickhouseoperatorconfigurations"}

var clickhouseoperatorconfigurationsKind = schema.GroupVersionKind{Group: "clickhouse.qingcloud.com", Version: "v1", Kind: "ClickHouseOperatorConfiguration"}

// Get takes name of the clickHouseOperatorConfiguration, and returns the corresponding clickHouseOperatorConfiguration object, and an error if there is any.
func (c *FakeClickHouseOperatorConfigurations) Get(name string, options v1.GetOptions) (result *clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clickhouseoperatorconfigurationsResource, c.ns, name), &clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration), err
}

// List takes label and field selectors, and returns the list of ClickHouseOperatorConfigurations that match those selectors.
func (c *FakeClickHouseOperatorConfigurations) List(opts v1.ListOptions) (result *clickhouseqingcloudcomv1.ClickHouseOperatorConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clickhouseoperatorconfigurationsResource, clickhouseoperatorconfigurationsKind, c.ns, opts), &clickhouseqingcloudcomv1.ClickHouseOperatorConfigurationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &clickhouseqingcloudcomv1.ClickHouseOperatorConfigurationList{ListMeta: obj.(*clickhouseqingcloudcomv1.ClickHouseOperatorConfigurationList).ListMeta}
	for _, item := range obj.(*clickhouseqingcloudcomv1.ClickHouseOperatorConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clickHouseOperatorConfigurations.
func (c *FakeClickHouseOperatorConfigurations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clickhouseoperatorconfigurationsResource, c.ns, opts))

}

// Create takes the representation of a clickHouseOperatorConfiguration and creates it.  Returns the server's representation of the clickHouseOperatorConfiguration, and an error, if there is any.
func (c *FakeClickHouseOperatorConfigurations) Create(clickHouseOperatorConfiguration *clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration) (result *clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clickhouseoperatorconfigurationsResource, c.ns, clickHouseOperatorConfiguration), &clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration), err
}

// Update takes the representation of a clickHouseOperatorConfiguration and updates it. Returns the server's representation of the clickHouseOperatorConfiguration, and an error, if there is any.
func (c *FakeClickHouseOperatorConfigurations) Update(clickHouseOperatorConfiguration *clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration) (result *clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clickhouseoperatorconfigurationsResource, c.ns, clickHouseOperatorConfiguration), &clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration), err
}

// Delete takes name of the clickHouseOperatorConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeClickHouseOperatorConfigurations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clickhouseoperatorconfigurationsResource, c.ns, name), &clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClickHouseOperatorConfigurations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clickhouseoperatorconfigurationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &clickhouseqingcloudcomv1.ClickHouseOperatorConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched clickHouseOperatorConfiguration.
func (c *FakeClickHouseOperatorConfigurations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clickhouseoperatorconfigurationsResource, c.ns, name, pt, data, subresources...), &clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clickhouseqingcloudcomv1.ClickHouseOperatorConfiguration), err
}
