// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clickhouseqingcloudcomv1 "github.com/TCeason/clickhouse-operator/pkg/apis/clickhouse.qingcloud.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClickHouseInstallations implements ClickHouseInstallationInterface
type FakeClickHouseInstallations struct {
	Fake *FakeClickhouseV1
	ns   string
}

var clickhouseinstallationsResource = schema.GroupVersionResource{Group: "clickhouse.qingcloud.com", Version: "v1", Resource: "clickhouseinstallations"}

var clickhouseinstallationsKind = schema.GroupVersionKind{Group: "clickhouse.qingcloud.com", Version: "v1", Kind: "ClickHouseInstallation"}

// Get takes name of the clickHouseInstallation, and returns the corresponding clickHouseInstallation object, and an error if there is any.
func (c *FakeClickHouseInstallations) Get(name string, options v1.GetOptions) (result *clickhouseqingcloudcomv1.ClickHouseInstallation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clickhouseinstallationsResource, c.ns, name), &clickhouseqingcloudcomv1.ClickHouseInstallation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clickhouseqingcloudcomv1.ClickHouseInstallation), err
}

// List takes label and field selectors, and returns the list of ClickHouseInstallations that match those selectors.
func (c *FakeClickHouseInstallations) List(opts v1.ListOptions) (result *clickhouseqingcloudcomv1.ClickHouseInstallationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clickhouseinstallationsResource, clickhouseinstallationsKind, c.ns, opts), &clickhouseqingcloudcomv1.ClickHouseInstallationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &clickhouseqingcloudcomv1.ClickHouseInstallationList{ListMeta: obj.(*clickhouseqingcloudcomv1.ClickHouseInstallationList).ListMeta}
	for _, item := range obj.(*clickhouseqingcloudcomv1.ClickHouseInstallationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clickHouseInstallations.
func (c *FakeClickHouseInstallations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clickhouseinstallationsResource, c.ns, opts))

}

// Create takes the representation of a clickHouseInstallation and creates it.  Returns the server's representation of the clickHouseInstallation, and an error, if there is any.
func (c *FakeClickHouseInstallations) Create(clickHouseInstallation *clickhouseqingcloudcomv1.ClickHouseInstallation) (result *clickhouseqingcloudcomv1.ClickHouseInstallation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clickhouseinstallationsResource, c.ns, clickHouseInstallation), &clickhouseqingcloudcomv1.ClickHouseInstallation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clickhouseqingcloudcomv1.ClickHouseInstallation), err
}

// Update takes the representation of a clickHouseInstallation and updates it. Returns the server's representation of the clickHouseInstallation, and an error, if there is any.
func (c *FakeClickHouseInstallations) Update(clickHouseInstallation *clickhouseqingcloudcomv1.ClickHouseInstallation) (result *clickhouseqingcloudcomv1.ClickHouseInstallation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clickhouseinstallationsResource, c.ns, clickHouseInstallation), &clickhouseqingcloudcomv1.ClickHouseInstallation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clickhouseqingcloudcomv1.ClickHouseInstallation), err
}

// Delete takes name of the clickHouseInstallation and deletes it. Returns an error if one occurs.
func (c *FakeClickHouseInstallations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clickhouseinstallationsResource, c.ns, name), &clickhouseqingcloudcomv1.ClickHouseInstallation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClickHouseInstallations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clickhouseinstallationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &clickhouseqingcloudcomv1.ClickHouseInstallationList{})
	return err
}

// Patch applies the patch and returns the patched clickHouseInstallation.
func (c *FakeClickHouseInstallations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *clickhouseqingcloudcomv1.ClickHouseInstallation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clickhouseinstallationsResource, c.ns, name, pt, data, subresources...), &clickhouseqingcloudcomv1.ClickHouseInstallation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*clickhouseqingcloudcomv1.ClickHouseInstallation), err
}
