/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/radondb/clickhouse-operator/pkg/apis/clickhouse.radondb.com/v1"
	scheme "github.com/radondb/clickhouse-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClickHouseBackupsGetter has a method to return a ClickHouseBackupInterface.
// A group's client should implement this interface.
type ClickHouseBackupsGetter interface {
	ClickHouseBackups(namespace string) ClickHouseBackupInterface
}

// ClickHouseBackupInterface has methods to work with ClickHouseBackup resources.
type ClickHouseBackupInterface interface {
	Create(ctx context.Context, clickHouseBackup *v1.ClickHouseBackup, opts metav1.CreateOptions) (*v1.ClickHouseBackup, error)
	Update(ctx context.Context, clickHouseBackup *v1.ClickHouseBackup, opts metav1.UpdateOptions) (*v1.ClickHouseBackup, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ClickHouseBackup, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ClickHouseBackupList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClickHouseBackup, err error)
	ClickHouseBackupExpansion
}

// clickHouseBackups implements ClickHouseBackupInterface
type clickHouseBackups struct {
	client rest.Interface
	ns     string
}

// newClickHouseBackups returns a ClickHouseBackups
func newClickHouseBackups(c *ClickhouseV1Client, namespace string) *clickHouseBackups {
	return &clickHouseBackups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clickHouseBackup, and returns the corresponding clickHouseBackup object, and an error if there is any.
func (c *clickHouseBackups) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ClickHouseBackup, err error) {
	result = &v1.ClickHouseBackup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clickhousebackups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClickHouseBackups that match those selectors.
func (c *clickHouseBackups) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ClickHouseBackupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ClickHouseBackupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clickhousebackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clickHouseBackups.
func (c *clickHouseBackups) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clickhousebackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clickHouseBackup and creates it.  Returns the server's representation of the clickHouseBackup, and an error, if there is any.
func (c *clickHouseBackups) Create(ctx context.Context, clickHouseBackup *v1.ClickHouseBackup, opts metav1.CreateOptions) (result *v1.ClickHouseBackup, err error) {
	result = &v1.ClickHouseBackup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clickhousebackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clickHouseBackup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clickHouseBackup and updates it. Returns the server's representation of the clickHouseBackup, and an error, if there is any.
func (c *clickHouseBackups) Update(ctx context.Context, clickHouseBackup *v1.ClickHouseBackup, opts metav1.UpdateOptions) (result *v1.ClickHouseBackup, err error) {
	result = &v1.ClickHouseBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clickhousebackups").
		Name(clickHouseBackup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clickHouseBackup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clickHouseBackup and deletes it. Returns an error if one occurs.
func (c *clickHouseBackups) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clickhousebackups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clickHouseBackups) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clickhousebackups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clickHouseBackup.
func (c *clickHouseBackups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClickHouseBackup, err error) {
	result = &v1.ClickHouseBackup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clickhousebackups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
