# Configuration for the ClickHouse cluster to be started
clickhouse:
  # default cluster name
  clusterName: all-nodes
  # shards count can not scale in this value.
  shardscount: 1
  # replicas count can not modify this value when the cluster has already created.
  replicascount: 2

  # ClickHouse server image configuration
  image: radondb/clickhouse-server:21.1.3.32
  imagePullPolicy: IfNotPresent

  resources:
    cpu: "0.5"
    memory: "1Gi"

  storage:
    capacity: "10Gi"
    # reclaim policy, value: Retain/Delete
    reclaimPolicy: Delete
    # storage class, leave blank to use default value in k8s
    storageClassName:

  # User Configuration
  user:
    - username: clickhouse
      password: c1ickh0use0perator
      networks:
        - "127.0.0.1"
        - "::/0"

  ports:
    tcp: 9000
    http: 8123

  # service, value: ClusterIP/NodePort/LoadBalancer
  # see https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  svc:
    type: NodePort


# Configuration for the Zookeeper to be used by ClickHouse
# Can not modify this value when the cluster has already created.
zookeeper:
  # If you want to create ZooKeeper by operator, use install = true
  install: true
  replicas: 3

  # ZooKeeper image configuration
  image: radondb/zookeeper:3.6.1
  imagePullPolicy: IfNotPresent

  resources:
    cpu: "0.5"
    memory: "1Gi"

  storage:
    capacity: "10Gi"
    # reclaim policy, value: Retain/Delete
    reclaimPolicy: Delete
    # storage class, leave blank to use default value in k8s
    storageClassName:

  ports:
    client: 2182
    server: 2889
    election: 3889

  # service, value: ClusterIP/NodePort/LoadBalancer
  # see https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  svc:
    type: NodePort

  # If you don’t want Operator to create a ZooKeeper cluster, we also provide a ZooKeeper deployment file,
  # you can customize the following configuration.
  # install: false
  # replicas: specify by yourself
  # image: radondb/zookeeper:3.6.2
  # imagePullPolicy: specify by yourself
  # resources:
  #   memory: specify by yourself
  #   cpu: specify by yourself
  #   storage: specify by yourself

# Configuration for the clickhouse backup
backup:
  # true for enable backup, false for disable
  enable: false

  # ClickHouse-backup image configuration
  image: radondb/clickhouse-backup:latest
  imagePullPolicy: IfNotPresent

  # Object storage related configuration required for backup
  # object storage must be compatible with AWS S3 protocol
  s3EndPoint: ""
  s3Bucket: ""
  s3Path: ""
  s3AccessKey: ""
  s3SecretKey: ""

  # The number of backups to keep, beyond which stale backups will be deleted
  backupKeep: 3

# Configuration for the busybox container
busybox:
  image: busybox
  imagePullPolicy: IfNotPresent
